/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
 /*!
  * @file   MorseEditViewController.h
  * @author Jean-David Gadina - www.xs-labs.com
  */

/* $Id$ */

#import "MorseEditViewController.h"

@implementation MorseEditViewController

@synthesize textView;
@synthesize navigationController;
@synthesize tableView;

- ( id )init
{
    if( ( self = [ super initWithNibName: @"MorseEditView" bundle: nil ] ) )
    {
        defaults = [ NSUserDefaults standardUserDefaults ];
    }
    
    return self;
}

-( IBAction )cancel: ( id )sender
{
    ( void )sender;
    
    [ textView resignFirstResponder ];
    [ navigationController popViewControllerAnimated: YES ];
}

-( IBAction )save: ( id )sender
{
    NSMutableArray * snippets;
    
    ( void )sender;
    
    if( [ textView.text length ] > 0 )
    {
        snippets = [ [ defaults objectForKey: @"morse-snippets" ] mutableCopy ];
        
        [ snippets addObject: textView.text ];
        [ defaults setObject: [ NSArray arrayWithArray: snippets ] forKey: @"morse-snippets" ];
        [ defaults synchronize ];
        [ snippets release ];
    }
    
    [ textView resignFirstResponder ];
    [ navigationController popViewControllerAnimated: YES ];
    [ tableView reloadData ];
}

- ( void )viewDidAppear: ( BOOL )animated
{
    ( void )animated;
    
    [ textView becomeFirstResponder ];
}

@end
