/*******************************************************************************
 * Copyright (c) 2011, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
 /*!
  * @file   MorseTableDataSource.m
  * @author Jean-David Gadina - www.xs-labs.com
  */

/* $Id$ */

#import "MorseTableDataSource.h"

@implementation MorseTableDataSource

- ( id )init
{
    if ( ( self = [ super init ] ) )
    {
        defaults = [ NSUserDefaults standardUserDefaults ];
    }
    
    return self;
}

- ( UITableViewCell * )tableView: ( UITableView * )tableView cellForRowAtIndexPath: ( NSIndexPath * )indexPath
{
    static NSString * CellIdentifier = @"Cell";
    UITableViewCell * cell;
    NSArray         * snippets;
    UIImageView     * backgroundView;
    
    snippets = [ defaults objectForKey: @"morse-snippets" ];
    
    ( void )tableView;
    ( void )indexPath;
    
    cell = [ tableView dequeueReusableCellWithIdentifier: CellIdentifier ];
    
    if( cell == nil )
    {
        cell                           = [ [ UITableViewCell alloc ] initWithStyle: UITableViewCellStyleValue1 reuseIdentifier: CellIdentifier ];
        cell.textLabel.textColor       = [ UIColor colorWithHue: ( CGFloat )0.00 saturation: ( CGFloat )0.00 brightness: ( CGFloat )1.00 alpha: ( CGFloat )1.00 ];
        cell.textLabel.backgroundColor = [ UIColor colorWithHue: ( CGFloat )0.00 saturation: ( CGFloat )0.00 brightness: ( CGFloat )1.00 alpha: ( CGFloat )0.00 ];
        
        [ cell.textLabel setFont: [ UIFont boldSystemFontOfSize: 16 ] ];
        
        backgroundView      = [ [ UIImageView alloc ] initWithImage: [ UIImage imageNamed: @"cell" ] ];
        cell.backgroundView = backgroundView;
        
        [ backgroundView autorelease ];
        [ cell autorelease ];
    }
    
    cell.textLabel.text = [ snippets objectAtIndex: [ indexPath row ] ];
    
    return cell;

}

- ( NSInteger )tableView: ( UITableView * )tableView numberOfRowsInSection: ( NSInteger )section
{
    NSArray * snippets;
    
    snippets = [ defaults objectForKey: @"morse-snippets" ];
    
    ( void )tableView;
    ( void )section;
    
    return [ snippets count ];
}

- ( void )tableView: ( UITableView * )tableView commitEditingStyle: ( UITableViewCellEditingStyle )editingStyle forRowAtIndexPath: ( NSIndexPath * )indexPath
{
    NSMutableArray * snippets;
    
    if( editingStyle == UITableViewCellEditingStyleDelete )
    {
        snippets = [ [ defaults objectForKey: @"morse-snippets" ] mutableCopy ];
        
        [ snippets removeObjectAtIndex: [ indexPath row ] ];
        [ defaults setObject: snippets forKey: @"morse-snippets" ];
        [ defaults synchronize ];
        [ snippets release ];
        [ tableView reloadData ];
    }
}

- ( BOOL )tableView: ( UITableView * )tableView canMoveRowAtIndexPath: ( NSIndexPath * )indexPath
{
    ( void )tableView;
    ( void )indexPath;
    
    return YES;
}

- ( void )tableView: ( UITableView * )tableView moveRowAtIndexPath: ( NSIndexPath * )fromIndexPath toIndexPath: ( NSIndexPath * )toIndexPath
{
    NSMutableArray * snippets;
    NSString       * text;
    
    snippets = [ [ defaults objectForKey: @"morse-snippets" ] mutableCopy ];
    text     = [ [ snippets objectAtIndex: [ fromIndexPath row ] ] retain ];
    
    [ snippets removeObjectAtIndex: [ fromIndexPath row ] ];
    [ snippets insertObject: text atIndex: [ toIndexPath row ] ];
    [ text release ];
    [ defaults setObject: snippets forKey: @"morse-snippets" ];
    [ defaults synchronize ];
    [ tableView reloadData ];
    [ snippets release ];
    [ tableView reloadData ];
}

@end
